### ISSUE TITLE
Key Error

### ISSUE THREAD

**Issue by csrajath** [btahir/Twitter-Pulse-Checker#1]
I am getting keyError executing See the error details below:
`KeyError                                  Traceback (most recent call last)`
`<ipython-input-30-ac1c323e2351> in <module>()`
`     28     if response['result'] == 'NEGATIVE':`
`     29       adj_polarity = response['polarity'] * - 1`
`---> 30     nerlst.append(row['tweet_dt'], row['topic'], row['id'], row['username'], row['name'], row['tweet'], ner['type'], ner['text'], response['result'], response['polarity'], `
`     31                    adj_polarity, row['like_count'], row['reply_count'], row['retweet_count'])`
KeyError: 'type'`

![See here](https://user-images.githubusercontent.com/23517359/90176756-16dc7b00-ddc7-11ea-8d69-a9f0524e9571.png)

I did surf around to debug but not of much help.

Any help is much appreciated.

**Comment by btahir** [comment]
Add this before the nerlst.append statement

```
    try:
      ner['type']
    except:
      ner['type'] = ''
```

You can leave the tag_type empty like above or call it something else.

**Comment by csrajath** [comment]
> Add this before the nerlst.append statement
> 
> ```
>     try:
>       ner['type']
>     except:
>       ner['type'] = ''
> ```
> 
> You can leave the tag_type empty like above or call it something else.

Okay, but doing so will not throw NER type (PER, LOC, MISC, ORG). It will just result like you see ![here](https://user-images.githubusercontent.com/23517359/90288918-76568b80-de98-11ea-9b0e-ab6e21653c65.png).

If we see your original ![notebook](https://user-images.githubusercontent.com/23517359/90289016-99813b00-de98-11ea-9ad2-3c85b547137c.png), It does throw tag type correctly. Why is 'type': 'Hashtag' being appended to ners list. Reckon something else need to be there instead of 'Hashtag'

**Comment by btahir** [comment]
Yeah it seems they have changed their APi. There is no type anymore but a harder to work with variable called labels. You can use something like this instead:

```
  # get hashtags
  hashtags = re.findall(r'#\w+', row['tweet'])
  if len(hashtags) >= 1:
    for hashtag in hashtags:
      ners.append({ 'labels': 'Hashtag', 'text': hashtag })
  
  for ner in ners:
    adj_polarity = response['polarity']
    if response['result'] == 'NEGATIVE':
      adj_polarity = response['polarity'] * -1
    if (ner['labels'] != 'Hashtag'):
      tag_type = str(ner['labels'][0]).split(' ')[0]
    nerlst.append([ row['tweet_dt'], row['topic'], row['id'], row['username'], 
                   row['name'], row['tweet'], tag_type, ner['text'], response['result'], 
                   response['polarity'], adj_polarity, row['like_count'], row['reply_count'], 
                  row['retweet_count'] ])
```
